Fri May 30 12:36:18 PM -03 2025

diff --git a/config/X11/xinitrc b/config/X11/xinitrc
--- a/config/X11/xinitrc
+++ b/config/X11/xinitrc
@@ -1,81 +1,71 @@
 #!/bin/sh
 
-userresources=$HOME/.config/X11/xresources
-usermodmap=$HOME/.config/X11/xmodmap
-sysresources=/etc/X11/xinit/.Xresources
-sysmodmap=/etc/X11/xinit/.Xmodmap
+userresources="$HOME/.config/X11/xresources"
+usermodmap="$HOME/.config/X11/xmodmap"
+sysresources="/etc/X11/xinit/.Xresources"
+sysmodmap="/etc/X11/xinit/.Xmodmap"
 
+# Function to start a program in the background if it exists
+start() {
+    if command -v "$1" > /dev/null 2>&1; then
+        # Check if the program is already running
+        if ! pidof -sx "$1" > /dev/null; then
+            "$@" &
+            echo "Started: $*" >> ~/xinit.log
+        else
+            echo "Already running: $*" >> ~/xinit.log
+        fi
+    else
+        echo "Executable not found: $1" >> ~/xinit.log
+    fi
+}
 
-if [ -f $sysresources ]; then
-    xrdb -merge $sysresources
+# Load system resources
+if [ -f "$sysresources" ]; then
+    start xrdb -merge "$sysresources"
 fi
 
-if [ -f $sysmodmap ]; then
-    xmodmap $sysmodmap
+if [ -f "$sysmodmap" ]; then
+    start xmodmap "$sysmodmap"
 fi
 
+# Load user resources
 if [ -f "$userresources" ]; then
-    xrdb -merge "$userresources"
+    start xrdb -merge "$userresources"
 fi
 
 if [ -f "$usermodmap" ]; then
-   xmodmap "$usermodmap" > ~/xmodap.works
+    start xmodmap "$usermodmap" > ~/xmodap.works
 fi
 
-# start some nice programs
-
-if [ -d /etc/X11/xinit/xinitrc.d ] ; then
- for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
-  [ -x "$f" ] && . "$f"
- done
- unset f
+# Start additional scripts if they exist
+if [ -d /etc/X11/xinit/xinitrc.d ]; then
+    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
+        [ -x "$f" ] && . "$f"
+    done
+    unset f
 fi
 
-# /usr/lib/plasma-dbus-run-session-if-needed startplasma-x11
+# Set DPI and other settings
+start xrandr --dpi 100
+start xset r rate 235 32
+start xset s off -dpms
 
-xrandr --dpi 100		# Set DPI. User may want to use a larger number for larger screens.
-#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/X11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
-xset r rate 235 32
-xset s off -dpms
+# Remap keys
+start setxkbmap -option caps:escape
+start xmodmap -e "keycode 34 = BackSpace"
 
-# setxkbmap -model br-abnt2-excyber -layout br-excyber
-
-# Remap Caps Lock to Escape
-setxkbmap -option caps:escape
-
-# Remap [ to Backspace
-xmodmap -e "keycode 34 = BackSpace"
-
-
-
-start() {
-  pidof -sx "$1" > /dev/null 2> /dev/null || "$@" &
-}
-
+# Start tmux and sxhkd
 start tmux
-
-# for program in $autostart; do
-# 	start "$program"
-# done >/dev/null 2>&1
-#
-# start xsettingsd
 start sxhkd
 
-# # Ensure that xrdb has finished running before moving on to start the WM/DE.
-# # [ -n "$xrdbpid" ] && wait "$xrdbpid"
-#
-# #start picom --config ~/.config/picom/picon.conf & # enable it if your pc is a little faster
+# Load custom keymap
+start xkbcomp "$HOME/.config/X11/xkb/keymap/excyber-keymap" "$DISPLAY"
 
-xkbcomp $HOME/.config/X11/xkb/keymap/excyber-keymap $DISPLAY
-# pkill picom &
-# pkill pipewire &
-# pkill pipewire-pulse &
-# pkill pulseaudio
-# pulseaudio --start
+# Uncomment to start additional services or applications
+# start pulseaudio --start
+# start google-chrome-stable
 
-# google-chrome-stable &
-# exec dwmblocks &
-#exec slstatus & # if you use slstatus instead of signal sending Giga Chad dwmblocks 
-
-# exec dwm
+# Start the window manager or desktop environment
 exec startxfce4
+
